/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Hp' at '30/9/20 6:36 PM' with Gradle 3.0
 *
 * @author Hp, @date 30/9/20 6:36 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
